<MyLayout>:
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        TextInput:
            id: calc_input
            text: '0'
            halign: 'right'
            font_size: 30
            size_hint: (1, .12)
        TextInput:
            id: calc_output
            text: '0'
            halign: 'right'
            font_size: 50
            size_hint: (1, .12)
        GridLayout:
            cols: 4
            rows: 6
            # rows

            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '%'
                on_press: root.percent()


            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: 'CE'
                on_press: root.clear()
            Button:
                id: clear
                size_hint: (.2, .2)
                font_size: 32
                text: 'C'
                on_press: root.clear()

            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: u'\u00AB'
                on_press: root.remove()

                # rows
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: 'x' + u'-\u00B9'
                on_press: root.inverse()
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: 'x' + u'\u00B2'
                on_press: root.squared()
            Button:
                id: clear
                size_hint: (.2, .2)
                font_size: 32
                text: u'\u00B2' + u'\u221A' + 'x'
                on_press: root.root_squared()

            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '÷'
                on_press: root.math_sign('÷')
# rows
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '7'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(7)
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '8'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(8)
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '9'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(9)
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: 'x'
                on_press: root.math_sign('x')
# rows
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '4'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(4)
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '5'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(5)
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '6'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(6)

            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '-'
                on_press: root.math_sign('-')
# rows
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '1'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(1)
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '2'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(2)
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '3'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(3)

            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '+'
                on_press: root.math_sign('+')
# rows
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '+/-'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.pos_neg()

            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '0'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.button_press(0)
            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '.'
                background_color: (157/255, 157/225, 157/225, 1)
                on_press: root.dot()

            Button:
                size_hint: (.2, .2)
                font_size: 32
                text: '='
                on_press: root.equals()
